# Generated by Django 6.0.7 on 2026-07-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_directmessage_mailattachment_messagerecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('bio_check', 'На проверке Биобезопасности'), ('waiting_contractor', 'Ожидает ответа от контрагента'), ('approved', 'Согласовано'), ('rejected', 'Въезд запрещен'), ('invalid_form', 'Неправильное заполнение формы')], default='new', max_length=30, verbose_name='Статус'),
        ),
    ]
