# Generated by Django 6.0.7 on 2026-09-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_directmessage_linked_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('bio_check', 'На проверке ОАБ'), ('waiting_contractor', 'Ожидает ответа от контрагента'), ('approved', 'Согласовано'), ('rejected', 'Въезд запрещен'), ('invalid_form', 'Неправильное заполнение формы')], default='new', max_length=30, verbose_name='Статус'),
        ),
    ]
